[platformio]
default_envs = uno

[env:uno]
platform      = atmelavr
board         = uno
framework     = arduino
upload_port   = /dev/tty.usbmodem1201
monitor_port  = /dev/tty.usbmodem1201
monitor_speed = 115200
lib_deps      =
    arduino-libraries/LiquidCrystal@^1.0.7
    adafruit/DHT sensor library@^1.4.6
